services:
  processing_service:
    build: .
    container_name: processing_service
    ports:
      - "8001:8001"
    env_file:
      - path: .env
        required: false
    environment:
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    depends_on:
      - minio
    volumes:
      - ./app:/app/app # Hot-reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - arxiv-shared

  minio:
    image: minio/minio
    container_name: arxiv_minio_silver
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin # pragma: allowlist secret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      arxiv-shared:
        aliases:
          - arxiv-minio

volumes:
  minio_data:
    external: true
    name: ingestion_service_minio_data

networks:
  arxiv-shared:
    external: true
